/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * In a single project build, this file is optional. However, it is recommended to include it.
 * For more details, take a look at the Gradle User Manual at https://docs.gradle.org/8.5/userguide/multi_project_builds.html
 */

rootProject.name = "gradle-demo"
